<?php
/**
 * DAO interface: UserConnectDAO
 * 
 * @author xucongbin
 * @since 2014-12-10
 * @package xkx
 * @version 1.0.0
 * @copyright Copyright (c) 2014 Baidu.com, Inc. All Rights Reserved.
 * @license Auto generated by Deagle 1.0.0
 */
interface UserConnectDAO{

    /**
     * insert UserConnect
     * @param UserConnect $userConnect
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function insert($userConnect);

    /**
     * insert many UserConnect
     * @param array<UserConnect> $userConnectList
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function insertMany($userConnectList);

    /**
     * update UserConnect
     * @param UserConnect $userConnect
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function update($userConnect);

    /**
     * update many UserConnect
     * @param array<UserConnect> $userConnectList
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function updateMany($userConnectList);

    /**
     * delete UserConnect
     * @param UserConnect $userConnect
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function delete($userConnect);

    /**
     * delete many UserConnect
     * @param array<UserConnect> $userConnectList
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function deleteMany($userConnectList);

    /**
     * get by id
     * @param string $id
     * @return UserConnect $userConnect
     * @throws DataAccessException
     */
    public function getById($id);

    /**
     * get list by id list
     * @param array<string> $idList
     * @return array<UserConnect> $userConnectList
     * @throws DataAccessException
     */
    public function getListByIdList($idList);

    /**
     * get list by condition
     * @param array $condition
     * @param string $orderBy
     * @param string $order
     * @param int $offset
     * @param int $limit
     * @return array<UserConnect> $UserConnectList
     * @throws DataAccessException
     */
    public function getList($condition, $orderBy, $order, $offset, $limit);

    /**
     * get count by condition
     * @param array $condition
     * @return int $count
     * @throws DataAccessException
     */
    public function getCount($condition);

    /**
     * get list by user-defined sql
     * @param string $sql
     * @return array<UserConnect> $userConnectList
     * @throws DataAccessException
     */
    public function getListBySql($sql);

    /**
     * build a/an UserConnect from db record
     * @param array $row
     * @return UserConnect $userConnect
     */
    public function build($row);

}
