<?php
/**
 * DAO interface: UserItemDAO
 * 
 * @author xucongbin
 * @since 2014-12-10
 * @package xkx
 * @version 1.0.0
 * @copyright Copyright (c) 2014 Baidu.com, Inc. All Rights Reserved.
 * @license Auto generated by Deagle 1.0.0
 */
interface UserItemDAO{

    /**
     * insert UserItem
     * @param UserItem $userItem
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function insert($userItem);

    /**
     * insert many UserItem
     * @param array<UserItem> $userItemList
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function insertMany($userItemList);

    /**
     * update UserItem
     * @param UserItem $userItem
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function update($userItem);

    /**
     * update many UserItem
     * @param array<UserItem> $userItemList
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function updateMany($userItemList);

    /**
     * delete UserItem
     * @param UserItem $userItem
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function delete($userItem);

    /**
     * delete many UserItem
     * @param array<UserItem> $userItemList
     * @return boolean, true on success & false on failed
     * @throws DataAccessException
     */
    public function deleteMany($userItemList);

    /**
     * get by id
     * @param string $id
     * @return UserItem $userItem
     * @throws DataAccessException
     */
    public function getById($id);

    /**
     * get list by id list
     * @param array<string> $idList
     * @return array<UserItem> $userItemList
     * @throws DataAccessException
     */
    public function getListByIdList($idList);

    /**
     * get list by condition
     * @param array $condition
     * @param string $orderBy
     * @param string $order
     * @param int $offset
     * @param int $limit
     * @return array<UserItem> $UserItemList
     * @throws DataAccessException
     */
    public function getList($condition, $orderBy, $order, $offset, $limit);

    /**
     * get count by condition
     * @param array $condition
     * @return int $count
     * @throws DataAccessException
     */
    public function getCount($condition);

    /**
     * get list by user-defined sql
     * @param string $sql
     * @return array<UserItem> $userItemList
     * @throws DataAccessException
     */
    public function getListBySql($sql);

    /**
     * build a/an UserItem from db record
     * @param array $row
     * @return UserItem $userItem
     */
    public function build($row);

}
