<?php
/**
 * Entity: UserConnect
 * 
 * @author xucongbin
 * @since 2014-12-10
 * @package xkx
 * @version 1.0.0
 * @copyright Copyright (c) 2014 Baidu.com, Inc. All Rights Reserved.
 * @license Auto generated by Deagle 1.0.0
 */
class UserConnect extends EntityObject{

    /**
     * id: 
     * @var int
     */
    protected $id;
    /**
     * 用户ID
     * @var string
     */
    protected $userId;
    /**
     * 第三方类型
     * @var string
     */
    protected $thirdParty;
    /**
     * 第三方帐号ID
     * @var string
     */
    protected $connectId;
    /**
     * 存储登录token信息
     * @var string
     */
    protected $accessToken;
    /**
     * 
     * @var string
     */
    protected $createTime;

    /**
     * __construct
     */
    public function __construct(){
        parent::__construct();
        $this->id = '0';
        $this->userId = '';
        $this->thirdParty = '';
        $this->connectId = '';
        $this->accessToken = '';
        $this->createTime = '';
    }

    /**
     * id getter
     * @return int $id
     */
    public function getId(){
        return $this->id;
    }

    /**
     * id setter
     * @param int $id
     * @return UserConnect
     */
    public function setId($id){
        $this->id = (string)$id;
        return $this;
    }

    /**
     * userId getter
     * @return string $userId
     */
    public function getUserId(){
        return $this->userId;
    }

    /**
     * userId setter
     * @param string $userId
     * @return UserConnect
     */
    public function setUserId($userId){
        $this->userId = (string)$userId;
        return $this;
    }

    /**
     * thirdParty getter
     * @return string $thirdParty
     */
    public function getThirdParty(){
        return $this->thirdParty;
    }

    /**
     * thirdParty setter
     * @param string $thirdParty
     * @return UserConnect
     */
    public function setThirdParty($thirdParty){
        $this->thirdParty = (string)$thirdParty;
        return $this;
    }

    /**
     * connectId getter
     * @return string $connectId
     */
    public function getConnectId(){
        return $this->connectId;
    }

    /**
     * connectId setter
     * @param string $connectId
     * @return UserConnect
     */
    public function setConnectId($connectId){
        $this->connectId = (string)$connectId;
        return $this;
    }

    /**
     * accessToken getter
     * @return string $accessToken
     */
    public function getAccessToken(){
        return $this->accessToken;
    }

    /**
     * accessToken setter
     * @param string $accessToken
     * @return UserConnect
     */
    public function setAccessToken($accessToken){
        $this->accessToken = (string)$accessToken;
        return $this;
    }

    /**
     * createTime getter
     * @return string $createTime
     */
    public function getCreateTime(){
        return $this->createTime;
    }

    /**
     * createTime setter
     * @param string $createTime
     * @return UserConnect
     */
    public function setCreateTime($createTime){
        $this->createTime = (string)$createTime;
        return $this;
    }

}
