<?php
/**
 * Entity: UserItem
 * 
 * @author xucongbin
 * @since 2014-12-10
 * @package xkx
 * @version 1.0.0
 * @copyright Copyright (c) 2014 Baidu.com, Inc. All Rights Reserved.
 * @license Auto generated by Deagle 1.0.0
 */
class UserItem extends EntityObject{

    /**
     * 
     * @var int
     */
    const EmailVerifiedYes = 1;   // 验证过
    const EmailVerifiedNo = 0;   // 没验证;

    /**
     * 
     * @var int
     */
    const SubscribeYes = 1;   // 订阅
    const SubscribeNo = 0;   // 不订阅;

    /**
     * id: 
     * @var string
     */
    protected $id;
    /**
     * 用户昵称
     * @var string
     */
    protected $nick;
    /**
     * 邮箱
     * @var string
     */
    protected $email;
    /**
     * 
     * @var int
     */
    protected $isEmailVerified;
    /**
     * 用户介绍
     * @var string
     */
    protected $intro;
    /**
     * 头像
     * @var array
     */
    protected $avatar;
    /**
     * 
     * @var int
     */
    protected $userLevel;
    /**
     * 
     * @var array
     */
    protected $tags;
    /**
     * 
     * @var int
     */
    protected $acceptSubscribeEmail;
    /**
     * 
     * @var string
     */
    protected $lastLoginTime;
    /**
     * 身份证号
     * @var string
     */
    protected $idCardNo;
    /**
     * 
     * @var string
     */
    protected $lastLoginIp;
    /**
     * 
     * @var string
     */
    protected $createTime;

    /**
     * __construct
     */
    public function __construct(){
        parent::__construct();
        $this->id = '0';
        $this->nick = '';
        $this->email = '';
        $this->isEmailVerified = 0;
        $this->intro = '';
        $this->avatar = array();
        $this->userLevel = 0;
        $this->tags = array();
        $this->acceptSubscribeEmail = 0;
        $this->lastLoginTime = '';
        $this->idCardNo = '';
        $this->lastLoginIp = '';
        $this->createTime = '';
    }

    /**
     * id getter
     * @return int $id
     */
    public function getId(){
        return $this->id;
    }

    /**
     * id setter
     * @param int $id
     * @return UserItem
     */
    public function setId($id){
        $this->id = (string)$id;
        return $this;
    }

    /**
     * nick getter
     * @return string $nick
     */
    public function getNick(){
        return $this->nick;
    }

    /**
     * nick setter
     * @param string $nick
     * @return UserItem
     */
    public function setNick($nick){
        $this->nick = (string)$nick;
        return $this;
    }

    /**
     * email getter
     * @return string $email
     */
    public function getEmail(){
        return $this->email;
    }

    /**
     * email setter
     * @param string $email
     * @return UserItem
     */
    public function setEmail($email){
        $this->email = (string)$email;
        return $this;
    }

    /**
     * isEmailVerified getter
     * @return int $isEmailVerified
     */
    public function getIsEmailVerified(){
        return $this->isEmailVerified;
    }

    /**
     * isEmailVerified setter
     * @param int $isEmailVerified
     * @return UserItem
     */
    public function setIsEmailVerified($isEmailVerified){
        $this->isEmailVerified = (int)$isEmailVerified;
        return $this;
    }

    /**
     * intro getter
     * @return string $intro
     */
    public function getIntro(){
        return $this->intro;
    }

    /**
     * intro setter
     * @param string $intro
     * @return UserItem
     */
    public function setIntro($intro){
        $this->intro = (string)$intro;
        return $this;
    }

    /**
     * avatar getter
     * @return array $avatar
     */
    public function getAvatar(){
        return $this->avatar;
    }

    /**
     * avatar setter
     * @param array $avatar
     * @return UserItem
     */
    public function setAvatar($avatar){
        $this->avatar = $avatar;
        return $this;
    }

    /**
     * userLevel getter
     * @return int $userLevel
     */
    public function getUserLevel(){
        return $this->userLevel;
    }

    /**
     * userLevel setter
     * @param int $userLevel
     * @return UserItem
     */
    public function setUserLevel($userLevel){
        $this->userLevel = (int)$userLevel;
        return $this;
    }

    /**
     * tags getter
     * @return array $tags
     */
    public function getTags(){
        return $this->tags;
    }

    /**
     * tags setter
     * @param array $tags
     * @return UserItem
     */
    public function setTags($tags){
        $this->tags = $tags;
        return $this;
    }

    /**
     * acceptSubscribeEmail getter
     * @return int $acceptSubscribeEmail
     */
    public function getAcceptSubscribeEmail(){
        return $this->acceptSubscribeEmail;
    }

    /**
     * acceptSubscribeEmail setter
     * @param int $acceptSubscribeEmail
     * @return UserItem
     */
    public function setAcceptSubscribeEmail($acceptSubscribeEmail){
        $this->acceptSubscribeEmail = (int)$acceptSubscribeEmail;
        return $this;
    }

    /**
     * lastLoginTime getter
     * @return string $lastLoginTime
     */
    public function getLastLoginTime(){
        return $this->lastLoginTime;
    }

    /**
     * lastLoginTime setter
     * @param string $lastLoginTime
     * @return UserItem
     */
    public function setLastLoginTime($lastLoginTime){
        $this->lastLoginTime = (string)$lastLoginTime;
        return $this;
    }

    /**
     * idCardNo getter
     * @return string $idCardNo
     */
    public function getIdCardNo(){
        return $this->idCardNo;
    }

    /**
     * idCardNo setter
     * @param string $idCardNo
     * @return UserItem
     */
    public function setIdCardNo($idCardNo){
        $this->idCardNo = (string)$idCardNo;
        return $this;
    }

    /**
     * lastLoginIp getter
     * @return string $lastLoginIp
     */
    public function getLastLoginIp(){
        return $this->lastLoginIp;
    }

    /**
     * lastLoginIp setter
     * @param string $lastLoginIp
     * @return UserItem
     */
    public function setLastLoginIp($lastLoginIp){
        $this->lastLoginIp = (string)$lastLoginIp;
        return $this;
    }

    /**
     * createTime getter
     * @return string $createTime
     */
    public function getCreateTime(){
        return $this->createTime;
    }

    /**
     * createTime setter
     * @param string $createTime
     * @return UserItem
     */
    public function setCreateTime($createTime){
        $this->createTime = (string)$createTime;
        return $this;
    }

}
