<div id="store-info-header">
				<div class="lefter">
					<h3 class="float_box"><span class="name">家乡人猫肉馆</span><span class="staic">正常营业</span></h3>
					<ul class="star-ul">
						<li class="all-star"></li>
						<li class="all-star"></li>
						<li class="all-star"></li>
						<li class="all-star"></li>
						<li class="half-star"></li>
					</ul>
				</div>
				<div class="righter">
					<div class="now-time">2013年12月12号 11:30</div>
				</div>
			</div>